import { Data } from "./types/types";

const data: Data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      rating: 2.9,
      numReviews: 10,
      description: "Hight quality product",
      countInStock: 3,
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "Hight quality product",
      countInStock: 5,
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "Hight quality product",
      countInStock: 2,
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 80,
      brand: "Nike",
      rating: 3.5,
      numReviews: 14,
      description: "Hight quality product",
      countInStock: 5,
    },
    {
      _id: "5",
      name: "Puma Slim Shirt",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 65,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "Hight quality product",
      countInStock: 0,
    },
    {
      _id: "6",
      name: "Adidas Slim Shirt",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "Hight quality product",
      countInStock: 3,
    },
  ],
};

export default data;
